const qrType = document.getElementById("qrType");
const inputFields = document.getElementById("inputFields");
const generateBtn = document.getElementById("generateBtn");
const qrPreview = document.getElementById("qrcode");
const downloadBtn = document.getElementById("downloadBtn");

let qr;


/* INPUT FIELD GENERATOR */

function updateInputsByType(){

let type = qrType.value;

if(type === "text" || type === "url"){

inputFields.innerHTML = `
<input type="text" id="mainInput" placeholder="Enter value">
`;

}

if(type === "phone"){

inputFields.innerHTML = `
<input type="text" id="phoneInput" placeholder="Enter phone number">
`;

}

if(type === "sms"){

inputFields.innerHTML = `
<input type="text" id="phoneInput" placeholder="Enter phone number">
<textarea id="messageInput" placeholder="Enter message"></textarea>
`;

}

if(type === "whatsapp"){

inputFields.innerHTML = `
<input type="text" id="phoneInput" placeholder="Enter WhatsApp number">
<textarea id="messageInput" placeholder="Enter message"></textarea>
`;

}

if(type === "email"){

inputFields.innerHTML = `
<input type="email" id="emailInput" placeholder="Enter email">
<input type="text" id="subjectInput" placeholder="Subject">
<textarea id="messageInput" placeholder="Message"></textarea>
`;

}

if(type === "upi"){

inputFields.innerHTML = `
<input type="text" id="upiId" placeholder="Enter UPI ID (example@upi)">
<input type="number" id="upiAmount" placeholder="Amount (optional)">
<textarea id="upiNote" placeholder="Note / message (optional)"></textarea>
`;

}

}


/* QR TYPE CHANGE */

qrType.addEventListener("change", updateInputsByType);


/* FIX BACK BUTTON ISSUE */

window.addEventListener("pageshow", () => {

updateInputsByType();

});


/* GENERATE QR */

generateBtn.addEventListener("click", () => {

qrPreview.innerHTML = "";

let type = qrType.value;
let data = "";


/* TEXT / URL */

if(type === "text" || type === "url"){

let value = document.getElementById("mainInput").value.trim();

if(value === ""){
alert("Please enter value");
return;
}

data = value;

}


/* PHONE */

if(type === "phone"){

let phone = document.getElementById("phoneInput").value.trim();

if(phone === ""){
alert("Enter phone number");
return;
}

data = "tel:" + phone;

}


/* SMS */

if(type === "sms"){

let phone = document.getElementById("phoneInput").value.trim();
let msg = document.getElementById("messageInput").value.trim();

if(phone === ""){
alert("Enter phone number");
return;
}

data = "SMSTO:" + phone + ":" + msg;

}


/* WHATSAPP */

if(type === "whatsapp"){

let phone = document.getElementById("phoneInput").value.trim();
let msg = document.getElementById("messageInput").value.trim();

if(phone === ""){
alert("Enter WhatsApp number");
return;
}

data = "https://wa.me/" + phone + "?text=" + encodeURIComponent(msg);

}


/* EMAIL */

if(type === "email"){

let email = document.getElementById("emailInput").value.trim();
let subject = document.getElementById("subjectInput").value.trim();
let msg = document.getElementById("messageInput").value.trim();

if(email === ""){
alert("Enter email");
return;
}

data =
"mailto:" + email +
"?subject=" + encodeURIComponent(subject) +
"&body=" + encodeURIComponent(msg);

}


/* UPI */

if(type === "upi"){

let upiId = document.getElementById("upiId").value.trim();
let amount = document.getElementById("upiAmount").value.trim();
let note = document.getElementById("upiNote").value.trim();

if(upiId === ""){
alert("Enter UPI ID");
return;
}

data = "upi://pay?pa=" + upiId;

if(amount){
data += "&am=" + amount;
}

if(note){
data += "&tn=" + encodeURIComponent(note);
}

}


/* CREATE QR */

qr = new QRCode(qrPreview, {

text: data,
width: 220,
height: 220

});

});


/* DOWNLOAD QR WITH PADDING + BORDER + BRANDING */

downloadBtn.addEventListener("click", () => {

const canvas = qrPreview.querySelector("canvas");

if(!canvas){

alert("Generate QR first");
return;

}

/* settings */

const padding = 30;
const brandingHeight = 45;

/* create new canvas */

const newCanvas = document.createElement("canvas");
const ctx = newCanvas.getContext("2d");

newCanvas.width = canvas.width + padding * 2;
newCanvas.height = canvas.height + padding * 2 + brandingHeight;


/* white background */

ctx.fillStyle = "#ffffff";
ctx.fillRect(0,0,newCanvas.width,newCanvas.height);


/* border */

ctx.strokeStyle = "#e0e0e0";
ctx.lineWidth = 2;

ctx.strokeRect(
1,
1,
newCanvas.width - 2,
canvas.height + padding*2 - 2
);


/* draw QR */

ctx.drawImage(
canvas,
padding,
padding
);


/* branding */

ctx.fillStyle = "#666";
ctx.font = "15px Arial";
ctx.textAlign = "center";

ctx.fillText(
"Generated by qrcdgenerator.in",
newCanvas.width/2,
canvas.height + padding*2 + 25
);


/* download */

const url = newCanvas.toDataURL("image/png");

const link = document.createElement("a");
link.href = url;
link.download = "qr-code.png";

document.body.appendChild(link);
link.click();
document.body.removeChild(link);

});